use_frameworks!

platform :ios, '9.0'

target 'ModuleStudy_CategoryKit_Example' do
  pod 'ModuleStudy_CategoryKit', :path => '../'

  target 'ModuleStudy_CategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
